# Generated by Django 5.2.1 on 2025-05-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('category', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_sender', models.IntegerField()),
                ('ad_receiver', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Ожидает', 'Stts Wait'), ('Принята', 'Stts Accepted'), ('Отклонена', 'Stts Denied')], default='Ожидает', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
