# Generated by Django 5.2.1 on 2025-05-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('Транспорт', 'Cars'), ('Недвижимость', 'Houses'), ('Личные вещи', 'Personal'), ('Для дома и дачи', 'For House'), ('Запчасти и аксессуары ', 'Spare Parts'), ('Электроника', 'Elect')], max_length=30),
        ),
    ]
