# Generated by Django 5.2.1 on 2025-05-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('cars', 'Транспорт'), ('houses', 'Недвижимость'), ('personal', 'Личные вещи'), ('for_house', 'Для дома и дачи'), ('spare_parts', 'Запчасти и аксессуары'), ('elect', 'Электроника')], max_length=30),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('wait', 'Ожидает'), ('accepted', 'Принята'), ('denied', 'Отклонена')], default='wait', max_length=20),
        ),
    ]
